export type getPokemonTypeProps = (value: string) => void;

export const getPokemonTypeColor: getPokemonTypeProps = (pokemonType) => {
  return pokemonType === "grass"
    ? "grass"
    : pokemonType === "fire"
    ? "fire"
    : pokemonType === "water"
    ? "water"
    : pokemonType === "poison"
    ? "poison"
    : pokemonType === "electric"
    ? "electric"
    : pokemonType === "ice"
    ? "ice"
    : pokemonType === "fighting"
    ? "fighting"
    : pokemonType === "ground"
    ? "ground"
    : pokemonType === "flying"
    ? "flying"
    : pokemonType === "psychic"
    ? "psychic"
    : pokemonType === "bug"
    ? "bug"
    : pokemonType === "rock"
    ? "rock"
    : pokemonType === "ghost"
    ? "ghost"
    : pokemonType === "dark"
    ? "dark"
    : pokemonType === "dragon"
    ? "dragon"
    : pokemonType === "steel"
    ? "steel"
    : pokemonType === "fairy"
    ? "fairy"
    : "normal";
};
